### ISSUE TITLE
Issue with "DBotPredictOutOfTheBoxV2" in @site/docs/reference/scripts/d-bot-predict-out-of-the-box-v2.md

### ISSUE THREAD

**Issue by ImanGitCA** [demisto/content-docs#1656]
## Describe the problem

* Page: [DBotPredictOutOfTheBoxV2](https://xsoar.pan.dev/docs/reference/scripts/d-bot-predict-out-of-the-box-v2)
* Source: https://github.com/demisto/content/blob/master//Packs/ML/Scripts/DBotPredictOutOfTheBoxV2/README.md

it seems the script returns an error as it cannot find punk_tab file from nltk:

 - Script failed to run: 
Error: [Traceback (most recent call last):
   
   File "<string>", line 278, in <module>
   File "<string>", line 262, in main
   File "<string>", line 131, in predict_phishing_words
   File "<string>", line 172, in predict_single_incident_full_output
   File "<string>", line 910, in filter_model_words
   File "/usr/local/lib/python3.10/site-packages/nltk/tokenize/__init__.py", line 142, in word_tokenize
    sentences = [text] if preserve_line else sent_tokenize(text, language)
   File "/usr/local/lib/python3.10/site-packages/nltk/tokenize/__init__.py", line 119, in sent_tokenize
    tokenizer = _get_punkt_tokenizer(language)
   File "/usr/local/lib/python3.10/site-packages/nltk/tokenize/__init__.py", line 105, in _get_punkt_tokenizer
    return PunktTokenizer(language)
   File "/usr/local/lib/python3.10/site-packages/nltk/tokenize/punkt.py", line 1744, in __init__
    self.load_lang(lang)
   File "/usr/local/lib/python3.10/site-packages/nltk/tokenize/punkt.py", line 1749, in load_lang
    lang_dir = find(f"tokenizers/punkt_tab/{lang}/")
   File "/usr/local/lib/python3.10/site-packages/nltk/data.py", line 579, in find
    raise LookupError(resource_not_found)
 LookupError: 
**********************************************************************
  Resource [93mpunkt_tab[0m not found.
  Please use the NLTK Downloader to obtain the resource:

  [31m>>> import nltk
  >>> nltk.download('punkt_tab')
  [0m
  For more information see: https://www.nltk.org/data.html

  Attempted to load [93mtokenizers/punkt_tab/english/[0m

  Searched in:
    - '/ml/nltk_data'
    - '/root/nltk_data'
    - '/usr/local/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/local/lib/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
**********************************************************************

] (2604) (2603) (2609)

## Environment
 - OS: [e.g. Windows]
 - Browser: [e.g. chrome, safari, firefox..]
 - Browser Version:
its part of a playbook used in XSOAR.

**Comment by ShirleyDenkberg** [comment]
@lperryp I see that you were the last one to work on this.  Can you take a look?

**Comment by ShirleyDenkberg** [comment]
@nkanon Can you assign this to the correct content person?

**Comment by nkanon** [comment]
> @nkanon Can you assign this to the correct content person?

@jlevypaloalto Is this related to you?
Thanks

**Comment by nkanon** [comment]
Hi @ImanGitCA, this should be opened as a bug through the support portal.
This issue will be closed as it is only served for documentation purposes.
Thanks
