### ISSUE TITLE
Issue with "JSON Feed" in @site/docs/reference/integrations/json-feed.md

### ISSUE THREAD

**Issue by scottbrumley** [demisto/content-docs#766]
## Describe the problem

* Page: [JSON Feed](https://xsoar.pan.dev/docs/reference/integrations/json-feed)
* Source: https://github.com/demisto/content/blob/master//Packs/FeedJSON/Integrations/FeedJSON/README.md

I've followed the example, but I keep getting this message. If you download the json as a file it pulls it in fine.

Error details
Script failed to run: 
Error: [Traceback (most recent call last):
   
   File "<string>", line 430, in <module>
   File "<string>", line 426, in main
   File "<string>", line 398, in feed_main
   File "<string>", line 6267, in return_error
 Exception: Error in JSON Feed integration [createIndicators() got an unexpected keyword argument 'noUpdate']
] (2604) (2603)

## Screenshots

![image](https://user-images.githubusercontent.com/6190372/130118151-a4670ffa-a8a4-47fc-9a37-cc97e57950bb.png)

## Environment
Chrome, MacOS

XSOAR
Version
6.2.0
Build
1271082
Source version
5da511df69c0aa766e6f9c9c93fcb2ff201d8c7a
Web client version
e8c233b8852875d395fc06360482a10e306453c3
Marketplace version
413872

 - OS: [e.g. Windows]
 - Browser: [e.g. chrome, safari, firefox..]
 - Browser Version:

**Comment by scottbrumley** [comment]
Small development.  I was able to get the !json-get-indicators using="JSON Feed_instance_1" command to work but the fetch_indicators is blowing up.  Also if you try to setup classifiers or mappings.
